### ISSUE TITLE
Can't seem to find docs

### ISSUE THREAD

**Issue by eedahl** [JoeRiel/maplev#3]
I want to try this thing but installing it seems pretty rough. The README is telling me there's a .html version of the docs, but I can only seem to find .texi files.

**Comment by JoeRiel** [comment]
I forgot to add them to the release. At one time they were part of the git repository, however, putting built files into a repository isn't a great practice. They are now in release 2.37, in the file maplev-built.zip. I added three formats: pdf, html, and info.  You should install the info file so that it is accessible via Emacs.
